### PR TITLE
Updated Mutation, Initialization, and some general clean + my version

### PR DESCRIPTION
**Pull request by grantmwilliams**
I was going through your code when i realized you can vectorize almost every part of your code. I began to go through and vectorize pieces here and there and then i realized it may be easier for me if i just included a vectorize version from scratch so you could compare the differences.

In your version of the GA I vectorized the way you initialize the population, i updated the way you were printing code, and i used a vectorized version of the mutation operation. The mutation itself decreased the run time on my machine from 7.5 seconds on average to 3.5 seconds on average. I planned on going through the crossover, fitness, and selection functions and doing the same thing, but i'm not sure when i'll have time to.

If you look at the folder i included of my version you'll see a vectorized version of the same algorithm (although yours is more robust in that it allows for a differing number of variables and mine does not). My version also does NOT print the pretty graph that yours does so that would be another reason mine is so much faster, but you can feel free to add that and see time differences.

On my machine your original algorithm ran in 7.5 seconds on average and mine is averaging around 0.07seconds for me.

I love genetic algorithms and they are currently part of my research interests so if you want to work together on some, or want to talk about them i'd love to collaborate!

Kind regards,
Grant

### CODE REVIEW

**Comment by alpsayin** [comment]
Hi Grant,

First of all, thanks for this. I will probably accept this pull request but I have to fully understand what's going on first. On a first look I can tell that you're definitely onto something. 

I wrote these codes back then for an assignment in 2012, I didn't really go for performance nor I'm sure If I actually had any idea about vectorization back then. I am also making a return to heuristic algorithms nowadays so I decided to open these sources and share my modifications as well.

I only wish you hadn't created a new folder and simply had overwritten the existing functions. In any case I will accept the pull request as is (there probably isn't any other way anyways). And then make some merging incorporating your ideas. And if you don't mind I'll also add your name to the license as well (which I have changed into an MIT license btw, because a colleague suggested I shouldn't really bother with licenses I don't understand well).

p.s. I'm glad these sources attracted at least some people

Take care and hope to hear from you again,

**Comment by grantmwilliams** [comment]
I started out but just updating a your functions here and there, but then i started to think it may be uncool of me to overwrite all of your code, so i went ahead and just wrote the functions in a separate algorithm. I thought it may be kind of cool to show you some of the performance difference you can get by using some of Matlab's built in functions to vectorize the code.

If you want i can help you go through and vectorize your main algorithm and functions (except for the plotting, I'm not actually sure how to use the plotting very well at all). I just wanted to show you an example of some ways you can speed up some of the code in your GA without undoing everything you did.

Maybe ill just do pull requests and update 1 function at a time and explain in a comment how to update the code? Either way i put my version i made in the folder so that after you're done looking at it you can easily just delete it!

**Comment by alpsayin** [comment]
Like I imagined, I have made a lot of changes. I haven't necessarily used all your codes but mostly the ideas :+1: Thanks again for the contribution. Take care :)

**Comment by grantmwilliams** [comment]
Looks really great man! Take care

**Pull request merged**
